package com.haha.main.retrofit

import com.google.gson.annotations.SerializedName

/**
 * `GET https://api.github.com/repos/{owner}/{repo}` 的仓库主体。
 * 未声明的 `*_url` 模板字段 Gson 会自动忽略。
 */
data class GithubRepoBean(
    val id: Long?,
    @SerializedName("node_id") val nodeId: String?,
    val name: String?,
    @SerializedName("full_name") val fullName: String?,
    @SerializedName("private") val isPrivate: Boolean?,
    val owner: GithubRepoOwnerBean?,
    @SerializedName("html_url") val htmlUrl: String?,
    val description: String?,
    val fork: Boolean?,
    val url: String?,
    @SerializedName("created_at") val createdAt: String?,
    @SerializedName("updated_at") val updatedAt: String?,
    @SerializedName("pushed_at") val pushedAt: String?,
    @SerializedName("git_url") val gitUrl: String?,
    @SerializedName("ssh_url") val sshUrl: String?,
    @SerializedName("clone_url") val cloneUrl: String?,
    @SerializedName("svn_url") val svnUrl: String?,
    val homepage: String?,
    val size: Long?,
    @SerializedName("stargazers_count") val stargazersCount: Int?,
    @SerializedName("watchers_count") val watchersCount: Int?,
    val language: String?,
    @SerializedName("has_issues") val hasIssues: Boolean?,
    @SerializedName("has_projects") val hasProjects: Boolean?,
    @SerializedName("has_downloads") val hasDownloads: Boolean?,
    @SerializedName("has_wiki") val hasWiki: Boolean?,
    @SerializedName("has_pages") val hasPages: Boolean?,
    @SerializedName("has_discussions") val hasDiscussions: Boolean?,
    @SerializedName("forks_count") val forksCount: Int?,
    @SerializedName("mirror_url") val mirrorUrl: String?,
    val archived: Boolean?,
    val disabled: Boolean?,
    @SerializedName("open_issues_count") val openIssuesCount: Int?,
    val license: String?,
    @SerializedName("allow_forking") val allowForking: Boolean?,
    @SerializedName("is_template") val isTemplate: Boolean?,
    @SerializedName("web_commit_signoff_required") val webCommitSignoffRequired: Boolean?,
    @SerializedName("has_pull_requests") val hasPullRequests: Boolean?,
    @SerializedName("pull_request_creation_policy") val pullRequestCreationPolicy: String?,
    val topics: List<String>?,
    val visibility: String?,
    val forks: Int?,
    @SerializedName("open_issues") val openIssues: Int?,
    val watchers: Int?,
    @SerializedName("default_branch") val defaultBranch: String?,
    @SerializedName("temp_clone_token") val tempCloneToken: String?,
    @SerializedName("network_count") val networkCount: Int?,
    @SerializedName("subscribers_count") val subscribersCount: Int?,
)

data class GithubRepoOwnerBean(
    val login: String?,
    val id: Long?,
    @SerializedName("node_id") val nodeId: String?,
    @SerializedName("avatar_url") val avatarUrl: String?,
    @SerializedName("gravatar_id") val gravatarId: String?,
    val url: String?,
    @SerializedName("html_url") val htmlUrl: String?,
    val type: String?,
    @SerializedName("user_view_type") val userViewType: String?,
    @SerializedName("site_admin") val siteAdmin: Boolean?,
)
