pluginManagement {
    includeBuild('ServiceRouterPlugin')
    plugins {
        id 'org.jetbrains.kotlin.multiplatform' version '2.2.0'
        id 'org.jetbrains.kotlin.android' version '2.2.0'
        id 'org.jetbrains.kotlin.plugin.compose' version '2.2.0'
        id 'org.jetbrains.compose' version '1.8.2'
    }
    repositories {
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
//dependencyResolutionManagement {
//    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
//    repositories {
//        google()
//        mavenCentral()
//    }
//}
rootProject.name = "HahaLearn"
include ':app'
include ':lib-common'
include ':shared'
include ':BluetoothSdk'
//include ':BaseUI'
include ':LlmSdk'
include ':speech-asr'
//include ':starrysky'
include ':ServiceAnnotationProcessor'
include ':ServiceAnnotation'
include ':ServiceApi'
include ':ServiceRuntime'
include ':ServiceImpl'
include ':BindViewAnnotation'
include ':BindViewProcessor'
include ':BindViewRuntime'
include ':JdkSpiApi'
include ':JdkSpiImpl'
include ':pluginapp'
include ':ServiceRouter'
include ':ServiceRouterProcessor'
include ':ServiceRouterAnnotation'
include ':ServiceRouterUtils'
include ':DOFLog'
// 引入 Flutter 模块
include ':flutterStudy'
//project(':flutterStudy').projectDir = file('../flutterStudy/.android/include_flutter.groovy') // 注意路径

setBinding(new Binding([gradle: this]))
evaluate(new File(
        settingsDir,
        'flutterStudy/.android/include_flutter.groovy'
))